import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import ReduxProvider from "@/redux/ReduxProvider";
import Navber from "@/components/Navbar";
// import { Inter } from 'next/font/google'
import { Noto_Sans_Thai } from "next/font/google";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Swensen's",
  description: "Generated by create next app",
  icons: "https://www.swensens1112.com/images/desktop-header-logo.svg"
};

const notoSansThai = Noto_Sans_Thai({
  weight: ["400", "700"],
  subsets: ["thai"],
  display: "swap",
});

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();


  return (
    <html lang={locale}>
      <body className={`min-h-screen ${notoSansThai.className}`}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ReduxProvider>
            <main className="overflow-auto">
              <Navber />
              <div className="pt-20 px-5 w-full min-h-[100vh] pb-0 container m-auto max-w-[1200px] lg:px-5 inner-container">
                {children}
              </div>
              <Footer />
            </main>
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
